# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f6d945fbadbb6885ca31b264927630d6af6777f034cc93485fec965ddd1db1d65b817bdbacb6b0085e25bf9d70007ca125fa484d967c008a1b3004a7ee3545a

test:
  secret_key_base: 07604be93a95e3b49dea85925db4fb4c6ad1e905d74a4bf66782234fb1528dfdda562628f1931bf50953839b5f60277e399d65977a8ca3aa9fd58957d100bf61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
